# docker-compose up
# -d (Detached mode: Run containers in the background, print new container names.)
# --no-recreate (If containers already exist, don't recreate them. Incompatible with --force-recreate.)
# --force-recreate (Recreate containers even if their configuration and image haven't changed.)
# https://docs.docker.com/compose/reference/up/

# $ docker-compose config
# $ docker-compose up -d --build
# $ docker-compose up -d --force-recreate --build

# GRANT ALL PRIVILEGES ON *.* TO 'user'@'%' WITH GRANT OPTION;
# GRANT RELOAD,PROCESS ON *.* TO 'user'@'%';
# FLUSH PRIVILEGES;

#version: '3.3'
version: '2.0'
services:
  mysql5.7:
    image: mysql:5.7.21
    container_name: mysql5.7
    restart: always
    ports:
      - '32771:3306'
    environment:
      MYSQL_ROOT_PASSWORD: geheimesPW12457!
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: geheimesPW12457!
    command: "--innodb_use_native_aio=0 --sql-mode=''"
    volumes:
      - '/c/Users/user/code/data_dir/mysql5.7_2:/var/lib/mysql'

